# Generated by Django 2.2.1 on 2019-06-28 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='kategori')),
                ('title', models.CharField(max_length=150, verbose_name='başlık')),
                ('content', models.TextField(verbose_name='icerik')),
                ('slug', models.SlugField(editable=False, max_length=75)),
                ('image', models.ImageField(blank=True, default='static/img/default_blog.jpg', null=True, upload_to='static/img/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='başlık')),
                ('text', models.TextField(verbose_name='yazı')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='yazılan tarih')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='paylaşılan tarih')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, default='static/img/default_blog.jpg', null=True, upload_to='static/img/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
            options={
                'verbose_name': 'Makale',
                'verbose_name_plural': 'Makaleler',
            },
        ),
    ]
