# Generated by Django 2.2.1 on 2019-05-20 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='başlık')),
                ('text', models.TextField(verbose_name='yazı')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='yazılan tarih')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='paylaşılan tarih')),
                ('tag', models.CharField(max_length=50, verbose_name='etiket')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
