# Generated by Django 2.2.1 on 2019-06-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190530_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(choices=[('1', 'Tazminat Hukuku'), ('2', 'Ceza Hukuku'), ('3', 'Medeni Hukuk'), ('4', 'Gayrimenkul Hukuku'), ('5', 'Vergi ve İdare Hukuku'), ('6', 'Bireysel Başvuru'), ('7', 'Arabulucuk'), ('8', 'Hukuk Haberleri')], max_length=50, verbose_name='kategori'),
        ),
    ]
