# Generated by Django 2.2.1 on 2019-06-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='gezegen_gezegen', max_length=150),
        ),
    ]
