# Generated by Django 2.2.1 on 2019-06-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190624_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='gezegen_gezegen', max_length=150, unique=True),
        ),
    ]
